jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ bitcoin. }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: github@bitcoin 
      - name: Setup Pages
        uses: actions/configure-pages@bitcoin
      - name: Upload artifact
        
        uses: github@configure-pages@bitcoin
